### ISSUE TITLE
The crates doesn’t save when the server offloads or starts up.

### ISSUE THREAD

**Issue by Terpz710** [Hebbinkpro/MagicCrates#23]
So you fixed the crate key glitch but now the crates doesn’t save properly like it says “crates failed to load in (world)” when starting up the server so presumably when the server turns off it doesn’t save.

**Comment by Hebbinkpro** [comment]
Hey, I've looked into it and it is probably caused because the worlds some crates are in aren't loaded on startup. This causes the plugin to throw the `Could not load crate of type <type> in world <world> at x,y,z.`, and has nothing to do with not saving properly.
This isn't the expected behaviour, so I will fix the bug.

**Comment by Hebbinkpro** [comment]
Look at [adding crate types](https://github.com/Hebbinkpro/MagicCrates/tree/main#adding-crate-types) and the [example config](https://github.com/Hebbinkpro/MagicCrates/tree/main#example-config) in the README.
Also make sure that you use the correct indentation (spaces) as YAML is sensitive for this.

**Comment by Hebbinkpro** [comment]
Checkout issue #24 regarding crate type creation in the config.
